### ISSUE TITLE
Biopython FastaWriter AttributeError Exception

### ISSUE THREAD

**Issue by muhammadabrar78** [biopython/biopython#2931]
### Setup

I am reporting a problem with Biopython 1.77.dev0, in conda environment as follow

```python
Python: 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0]
CPython
OS: Linux-4.15.0-99-generic-x86_64-with-debian-buster-sid
Biopython : 1.77.dev0
```
I am using the following conda environment
```
     active environment : bioinformatics
    active env location : /home/abrar/anaconda3/envs/bioinformatics
            shell level : 2
       user config file : /home/abrar/.condarc
    populated config files : /home/abrar/.condarc
    conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/abrar/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/abrar/anaconda3/pkgs
                          /home/abrar/.conda/pkgs
       envs directories : /home/abrar/anaconda3/envs
                          /home/abrar/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/4.15.0-99-generic ubuntu/18.04.1 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
### Expected behaviour
I am writing the PDB protein sequence fragment to fasta format as below. 
```
from Bio.SeqIO import PdbIO, FastaIO

def get_fasta(pdb_file, fasta_file, transfer_ids=None):
    fasta_writer = FastaIO.FastaWriter(fasta_file)
    fasta_writer.write_header()
    for rec in PdbIO.PdbSeqresIterator(pdb_file):
        if len(rec.seq) == 0:
            continue
        if transfer_ids is not None and rec.id not in transfer_ids:
            continue
        print(rec.id, rec.seq, len(rec.seq))
        fasta_writer.write_record(rec)
        
get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])
get_fasta(open('pdb1olg.ent'), open('1olg.fasta', 'w'), transfer_ids=['1OLG:B'])
get_fasta(open('pdb1ycq.ent'), open('1ycq.fasta', 'w'), transfer_ids=['1YCQ:B'])
```
 IN biopython 1.76 it works fine and write all the information in their respectives files which should be its normal behaviour. 
### Actual behaviour
However, the biopython1.77.dev0 raised the following exception. 
```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-8ecf92753ac9> in <module>
     12         fasta_writer.write_record(rec)
     13 
---> 14 get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])
     15 get_fasta(open('pdb1olg.ent'), open('1olg.fasta', 'w'), transfer_ids=['1OLG:B'])
     16 get_fasta(open('pdb1ycq.ent'), open('1ycq.fasta', 'w'), transfer_ids=['1YCQ:B'])

<ipython-input-9-8ecf92753ac9> in get_fasta(pdb_file, fasta_file, transfer_ids)
     10             continue
     11         print(rec.id, rec.seq, len(rec.seq))
---> 12         fasta_writer.write_record(rec)
     13 
     14 get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])

~/anaconda3/envs/bioinformatics/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py in write_record(self, record)
    303     def write_record(self, record):
    304         """Write a single Fasta record to the file."""
--> 305         assert self._header_written
    306         assert not self._footer_written
    307         self._record_written = True

AttributeError: 'FastaWriter' object has no attribute '_header_written'
```
### Steps to reproduce
The given code is part of the bioinformatics with python cookbook  [here](https://github.com/PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition/blob/master/Chapter07/PDB.ipynb) and the issue is at cell no 11. (the last part of the PDB.ipynb)

**Comment by peterjc** [comment]
Using the ``FastaWriter`` directly is unusual when ``Bio.SeqIO.write(...)`` would be typical, but that should still work.

**Comment by peterjc** [comment]
Can you be more precise about which version of Biopython you have (e.g. a commit hash), the version indicates somewhere between the Biopython 1.76 and 1.77 releases. Testing with the latest release 1.77 might help.

**Comment by peterjc** [comment]
Using the high level API, I might have written this:

```python
from Bio import SeqIO

def get_fasta(pdb_file, fasta_file, transfer_ids=None):
    with open(fasta_file, "w") as out_handle:
        for rec in SeqIO.parse(pdb_file, "pdb-seqres"):
            if len(rec.seq) == 0:
                continue
            if transfer_ids is not None and rec.id not in transfer_ids:
                continue
            print(rec.id, rec.seq, len(rec.seq))
            SeqIO.write(rec, out_handle, "fasta")
        
get_fasta(open('pdb1tup.ent'), open('1tup.fasta', 'w'), transfer_ids=['1TUP:B'])
get_fasta(open('pdb1olg.ent'), open('1olg.fasta', 'w'), transfer_ids=['1OLG:B'])
get_fasta(open('pdb1ycq.ent'), open('1ycq.fasta', 'w'), transfer_ids=['1YCQ:B'])
```

**Comment by peterjc** [comment]
Minimal test case:

```
$ python -c 'from Bio.SeqIO.FastaIO import FastaWriter; f = FastaWriter("tmp.txt"); f.write_header(); f.write_records("SeqRecord goes here")'
...
AttributeError: 'FastaWriter' object has no attribute '_header_written'
```

Should complain that it was not given a ``SeqRecord`` object.

**Comment by peterjc** [comment]
Found it, 07051e7a9047299de1c84086102c207452cca9c4 worked but 5c964a7ba6881a30e8d9efa4233ba484ad6939cc failed from #2717 

It was initially this change:

``SequentialSequenceWriter.__init__(self, target)`` --> ``super().__init__(target)``

I have a fix coming...

**Comment by muhammadabrar78** [comment]
> Using the high level API, I might have written this:
> 
> ```python
> from Bio import SeqIO
> 
> def get_fasta(pdb_file, fasta_file, transfer_ids=None):
>     with open(fasta_file, "w") as out_handle:
>         for rec in SeqIO.parse(pdb_file, "pdb-seqres"):
>             if len(rec.seq) == 0:
>                 continue
>             if transfer_ids is not None and rec.id not in transfer_ids:
>                 continue
>             print(rec.id, rec.seq, len(rec.seq))
>             SeqIO.write(rec, out_handle, "fasta")
>         
> # now passing filenames
> get_fasta('pdb1tup.ent', '1tup.fasta', transfer_ids=['1TUP:B'])
> get_fasta('pdb1olg.ent', '1olg.fasta', transfer_ids=['1OLG:B'])
> get_fasta('pdb1ycq.ent', '1ycq.fasta', transfer_ids=['1YCQ:B'])
> ```



> Using the high level API, I might have written this:
> 
> ```python
> from Bio import SeqIO
> 
> def get_fasta(pdb_file, fasta_file, transfer_ids=None):
>     with open(fasta_file, "w") as out_handle:
>         for rec in SeqIO.parse(pdb_file, "pdb-seqres"):
>             if len(rec.seq) == 0:
>                 continue
>             if transfer_ids is not None and rec.id not in transfer_ids:
>                 continue
>             print(rec.id, rec.seq, len(rec.seq))
>             SeqIO.write(rec, out_handle, "fasta")
>         
> # now passing filenames
> get_fasta('pdb1tup.ent', '1tup.fasta', transfer_ids=['1TUP:B'])
> get_fasta('pdb1olg.ent', '1olg.fasta', transfer_ids=['1OLG:B'])
> get_fasta('pdb1ycq.ent', '1ycq.fasta', transfer_ids=['1YCQ:B'])
> ```

This worked for me.

**Comment by muhammadabrar78** [comment]
> Using the high level API, I might have written this:
> 
> ```python
> from Bio import SeqIO
> 
> def get_fasta(pdb_file, fasta_file, transfer_ids=None):
>     with open(fasta_file, "w") as out_handle:
>         for rec in SeqIO.parse(pdb_file, "pdb-seqres"):
>             if len(rec.seq) == 0:
>                 continue
>             if transfer_ids is not None and rec.id not in transfer_ids:
>                 continue
>             print(rec.id, rec.seq, len(rec.seq))
>             SeqIO.write(rec, out_handle, "fasta")
>         
> # now passing filenames
> get_fasta('pdb1tup.ent', '1tup.fasta', transfer_ids=['1TUP:B'])
> get_fasta('pdb1olg.ent', '1olg.fasta', transfer_ids=['1OLG:B'])
> get_fasta('pdb1ycq.ent', '1ycq.fasta', transfer_ids=['1YCQ:B'])
> ```

This worked for me

**Comment by peterjc** [comment]
Great - the main reason I would recommend the ``SeqIO.parse`` / ``SeqIO.read`` approach is the code stays the same if you switch formats, but it is also more tested.

Thank you for reporting the bug with using ``FastaWriter`` directly 👍

**Comment by peterjc** [comment]
This is now fixed with #2932, during which I was reminded that we've labeled ``FastaWriter`` as obsolete, so it is likely to be formally deprecated with a warning on use, and later removed.
https://biopython.org/wiki/Deprecation_policy

If you are able to update your Biopython to the latest from git, and retest the original example, that would be appreciated.

**Comment by muhammadabrar78** [comment]
Thank you so much peterjc and mdehoon  for you time. I mean it, because it took me a lot of time to merely uninstall the old version (which I install using setup.py)  and install the new one and you people are helping us with deprecated modules. 
It is working now perfectly with the FastaWriter directly.

**Comment by peterjc** [comment]
Thanks for confirming the fix is working with the original example, I'll close this now.
