### ISSUE TITLE
Fails to build with Python3.12

### ISSUE THREAD

**Issue by tillea** [biopython/biopython#4532]
### Setup

The Debian packaged biopython received a [bug report](bugs.debian.org/1057809) which contains the output:

    x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2
    -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat
    -Werror=format-security -fcf-protection -g -fwrapv -O2 -g -O2
    -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong
    -fstack-clash-protection -Wformat -Werror=format-security
    -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
    -I/<<PKGBUILDDIR>>/pysam -I/usr/include -I/<<PKGBUILDDIR>>/samtools
    -I/<<PKGBUILDDIR>>/samtools/lz4 -I/<<PKGBUILDDIR>>/bcftools
    -I/<<PKGBUILDDIR>> -I/usr/include/python3.12 -c pysam/libchtslib.c -o
    build/temp.linux-x86_64-cpython-312/pysam/libchtslib.o -Wno-unused
    -Wno-strict-prototypes -Wno-sign-compare
    -Wno-error=declaration-after-statement
    pysam/libchtslib.c: In function ‘__pyx_f_5pysam_10libchtslib_set_verbosity’:
    pysam/libchtslib.c:1387:32: error: ‘_PyCFrame’ has no member named
    ‘use_tracing’
     1387 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    pysam/libchtslib.c:958:43: note: in definition of macro ‘unlikely’
      958 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    pysam/libchtslib.c:1426:15: note: in expansion of macro ‘__Pyx_IsTracing’
     1426 |           if (__Pyx_IsTracing(tstate, 1, 1)) {\
          |               ^~~~~~~~~~~~~~~

### Expected behaviour

It would be great if biopython would build with Python3.12

### Steps to reproduce

Just try to build against Python3.12.

Kind regards, Andreas.

**Comment by peterjc** [comment]
Did you file this against Biopython rather than pysam in error?

I was able to build wheels for Biopython 1.81 on Python 3.12 too, see https://github.com/biopython/biopython-wheels/

We are building against Python 3.12 on the latest branch (see GitHub actions).

**Comment by tillea** [comment]
> Did you file this against Biopython rather than pysam in error?
Argh, sorry for the noise, Andreas.
