### PR TITLE
Fix PairwiseAligner compiler warnings on switch statements

### PR DESCRIPTION
**Pull request by mdehoon**
use `__slots__` on `PairwiseAligner`, instead of reinventing the wheel.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #...

### CODE REVIEW

**Comment by mdehoon** [comment]
@peterjc  How old is pypy3 used by Travis? With the current version of pypy3.6 for Mac, `__slots__` is behaving as expected.

**Comment by peterjc** [comment]
From the TravisCI logging for pypy3, where it is available under the binary name ``python``:

```
$ python --version
Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
[PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

So only PyPy 7.3.1 rather than 7.3.3 which is the latest from https://www.pypy.org/download.html

Which version of pypy do you have locally?

**Comment by mdehoon** [comment]
@peterjc  Thanks.
> Which version of pypy do you have locally?

I have 7.3.3 on Mac.

**Comment by mdehoon** [comment]
@peterjc Thanks.
> Which version of pypy do you have locally?

`__slots__` also  works correctly with pypy version 7.3.3 on Linux.

**Comment by peterjc** [comment]
The TravisCI documentation on this is out of date,
https://docs.travis-ci.com/user/languages/python/#pypy-support

Until now the TravisCI provided PyPy has been recent enough to just work. In the past we had to actively install a later version than was readily provided. It was a hassle to setup though...

**Comment by mdehoon** [comment]
With the exact same version of PyPy as on Travis, `__slots__` is behaving as expected:

```
$ ./pypy3
Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
[PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> class A:
....     __slots__ = ()
....     
>>>> a = A()
>>>> a.x = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'x'
>>>> 
```

Not sure what is going on here. With Python 2.7, `__slots__ ` misbehaves:
```
$ ./pypy 
Python 2.7.18 (a29ef73f9b32, Nov 09 2020, 18:42:06)
[PyPy 7.3.3 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> class A:
....     __slots__ = ()
....     
>>>> a = A()
>>>> a.x = 5
>>>> 
```

**Comment by mdehoon** [comment]
It seems that `__slots__` behaves differently on PyPy compared to CPython if the class inherits from a class implemented in C. Perhaps this can be solved, but then we may be relying on a side-effect of `__slots__` rather than its intended purpose.

**Comment by peterjc** [comment]
Avoiding accidental side effects of the CPython implementation is probably wise.

Is there a PyPy issue about this worth linking to and/or commenting on?

**Comment by mdehoon** [comment]
@peterjc 
> Is there a PyPy issue about this worth linking to and/or commenting on?
I haven't seen one.

**Comment by peterjc** [comment]
I had a look on https://foss.heptapod.net/pypy/pypy/-/issues but didn't see anything obvious.

Note as per https://foss.heptapod.net/pypy/pypy/-/issues/2771 the Python 2 behaviour about blocking undeclared attributes requires explicitly using new classes (by subclassing object).
