### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'status'

### ISSUE THREAD

**Issue by bitcometz** [biopython/biopython#2271]
hello, I want to use Entrez.efetch to download the whole rice ESTs for NCBI.
Firstly, I download all the accession_ids from NCBI.
Since the accession_ids are too many, I split them to several files.

When I run just one task to download the seqs, it work well.
However, if I run more than two tasks, then all the tasks report an error：

```
Traceback (most recent call last):
  File "download_seqs_from_ncib_with_accid.py", line 26, in <module>
    main(sys.argv)
  File "download_seqs_from_ncib_with_accid.py", line 21, in main
    handle = Entrez.efetch(db=database, id=line, rettype='fasta', retmode="text")
  File "/conda_envs/python2_env/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 195, in efetch
    return _open(cgi, variables, post=post)
  File "/conda_envs/python2_env/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 564, in _open
    and exception.status // 100 == 4:
**AttributeError: 'HTTPError' object has no attribute 'status'**
```

Here is my code:

```python
def main(argv=sys.argv):

    file = argv[1]
    outfile = argv[2]
    output_handle = open(outfile, "w")
    database = 'nucleotide'

    with open(file,"r") as fin:
        for line in fin:
            line = line.strip('\n')
            print(line)
            handle = Entrez.efetch(db=database, id=line, rettype='fasta', retmode="text")
            record = SeqIO.read(handle,'fasta')
            SeqIO.write(record, output_handle, 'fasta')

if __name__ == "__main__":
        main(sys.argv)
```

Could anyone help with this problem ? Thanks !!!

**Comment by chris-rands** [comment]
Instead of splitting to several files you could try running on a single file and setting the `Entrez.api_key`: https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/

If you have a really large number of accessions then it might be best to download flat files of the data and parse them rather than querying through Entrez

**Comment by peterjc** [comment]
The problem with the error handling looks like a duplicate of #2257 (logged earlier this month, but closed without addressing the error handling).

Reading https://docs.python.org/2/library/urllib2.html#urllib2.HTTPError and https://docs.python.org/3/library/urllib.error.html makes me wonder why it isn't ``.code`` here?

@mdehoon is this a bug introduced with #2164 which added the retry support?

**Comment by peterjc** [comment]
@bitcometz Biopython will respect the NCBI Entrez rate limits, but if you run two separate tasks at the same time on the same machine, your machine will probably be making requests too often. The NCBI might block you - that might be the cause of the error message (which we are not handling properly)?

As Chris suggests, for large download tasks there are usually better ways than a loop and one ``efetch`` query per sequence. The Entrez batch support is worth looking at (i.e. combine ``epost`` and ``efetch`` to get multiple records at once).

**Comment by mdehoon** [comment]
I believe the code checking for the status of an HTTPError was added in commit #4e186c0. @ExplodingCabbage  , can you have a look?

**Comment by ExplodingCabbage** [comment]
Huh. Yeah, looks like my error handling is broken. I didn't know there was any circumstance in which a `HTTPError` could not have a `.status` attribute. I'll make figuring out how the heck that happens and fixing it my highest priority this weekend.

**Comment by ExplodingCabbage** [comment]
Ah, this is Python 2 vs 3 thing. `HTTPError.status` only exists in Python 3. I ought to have used HTTPError.code instead, which exists in both versions (and is the only one of the two attributes to be documented even in [the docs for Python 3](https://docs.python.org/3/library/urllib.error.html#urllib.error.HTTPError)!) Oops. At least it's trivial to fix!

**Comment by peterjc** [comment]
Mystery solved - looks like a Python 3 documentation issue with ``.status`` not being described. Thanks for resolving this.
