### ISSUE TITLE
Bio/Align/_aligners.c compiler error: missing field 'ml_meth' initializer.

### ISSUE THREAD

**Issue by DJV512** [biopython/biopython#4466]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.12.0 (main, Oct 17 2023, 20:49:13) [GCC 11.4.0]
CPython Linux-6.2.0-1014-azure-x86_64-with-glibc2.35

(The above info is for a GitHub code space, but I get the same install error on my Mac and my Windows computers.)

### Expected behaviour

"pip install biopython" does not work when using python 3.12. The above system information is from the Github code space I am currently using, but the same issue happens on my Windows computer. On the windows computer, biopython worked just fine until I updated to Python 3.12. I solved the issue (for now) by setting up two separate environments in one project folder, one with python 3.11 and one with python 3.12. When the python 3.11 environment is activated, it installs and runs biopython just fine, but when the 3.12 environment is activated, it won't install biopython. Instead, it says that it fails to build the wheel. See below: 

### Actual behaviour

clang -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -ferror-limit=1 -gdwarf-4 -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-gnu-folding-constant -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wshadow -fPIC -I/usr/local/include/python3.12 -c Bio/Align/_aligners.c -o build/temp.linux-x86_64-cpython-312/Bio/Align/_aligners.o
      Bio/Align/_aligners.c:1659:10: error: missing field 'ml_meth' initializer [-Werror,-Wmissing-field-initializers]
          {NULL}  /* Sentinel */
               ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for biopython
  Running setup.py clean for biopython
Failed to build biopython
ERROR: Could not build wheels for biopython, which is required to install pyproject.toml-based projects

### Steps to reproduce

Using python 3.12, run "pip install biopython."

**Comment by peterjc** [comment]
I suspect you'd have trouble building from source with Python 3.11 too, but you don't see that because we provide a wheel. i.e. My guess is this is a problem from a very recent compiler being stricter than before.

The compiler error is probably something @mdehoon needs to look at:

```
clang -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -ferror-limit=1 -gdwarf-4 -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-gnu-folding-constant -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wshadow -fPIC -I/usr/local/include/python3.12 -c Bio/Align/_aligners.c -o build/temp.linux-x86_64-cpython-312/Bio/Align/_aligners.o
Bio/Align/_aligners.c:1659:10: error: missing field 'ml_meth' initializer [-Werror,-Wmissing-field-initializers]
```

Looks like several issues here, probably the simplest fix is for us to try to make some wheels for Python 3.12 on PyPI https://pypi.org/project/biopython/#files (which may or may not run into this issue) and/or hurry up with Biopython 1.82 #4312 (which I'm pretty sure seems to be working on Python 3.12).

**Comment by DJV512** [comment]
Thanks for the response! I'm glad to see that it's not just something I'm doing wrong. Good luck with the fix!

**Comment by peterjc** [comment]
Painful, but I am making headway on Python 3.12 wheels at https://github.com/biopython/biopython-wheels/pull/19

**Comment by peterjc** [comment]
We should have Python 3.12 wheels for Biopython 1.81 on PyPI later tonight...

**Comment by peterjc** [comment]
We now have wheels for Python 3.12 on PyPI for Biopython 1.81.
https://pypi.org/project/biopython/1.81/#files

I'm going to leave this issue open but re-title it to focus on the compiler error: missing field 'ml_meth' initializer.

**Comment by DJV512** [comment]
Wow that was fast! Thank you so much!

**Comment by mdehoon** [comment]
This will be fixed by #4479 and #4482 , though some additional compiler warnings may appear once those two PRs are committed.
